# Generated by Django 4.2.7 on 2025-08-07 13:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'type de cuisine',
                'verbose_name_plural': 'types de cuisine',
                'db_table': 'cuisine_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='image')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='calories')),
                ('allergens', models.JSONField(blank=True, default=list, verbose_name='allergènes')),
                ('dietary_tags', models.JSONField(blank=True, default=list, verbose_name='tags alimentaires')),
                ('preparation_time', models.PositiveIntegerField(default=15, verbose_name='temps de préparation (minutes)')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='note moyenne')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name="nombre total d'avis")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.category')),
            ],
            options={
                'verbose_name': 'plat',
                'verbose_name_plural': 'plats',
                'db_table': 'menu_items',
            },
        ),
        migrations.CreateModel(
            name='MenuItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='modificateur de prix')),
                ('is_required', models.BooleanField(default=False, verbose_name='obligatoire')),
                ('max_selections', models.PositiveIntegerField(default=1, verbose_name='sélections maximum')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='restaurants.menuitem')),
            ],
            options={
                'verbose_name': 'option de plat',
                'verbose_name_plural': 'options de plats',
                'db_table': 'menu_item_options',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('address', models.TextField(verbose_name='adresse complète')),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='site web')),
                ('opening_hours', models.JSONField(default=dict, verbose_name="horaires d'ouverture")),
                ('is_open', models.BooleanField(default=True, verbose_name='ouvert')),
                ('is_verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('delivery_radius', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='rayon de livraison (km)')),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='commande minimum')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='frais de livraison')),
                ('preparation_time', models.PositiveIntegerField(default=30, verbose_name='temps de préparation (minutes)')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='note moyenne')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name="nombre total d'avis")),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='nombre total de commandes')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/', verbose_name='logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/', verbose_name='image de couverture')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuisine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='restaurants.cuisinetype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'db_table': 'restaurants',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('promotion_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed_amount', 'Montant fixe'), ('free_delivery', 'Livraison gratuite'), ('buy_one_get_one', 'Achetez un, obtenez un gratuit')], max_length=20, verbose_name='type de promotion')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valeur de la réduction')),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='commande minimum')),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='réduction maximum')),
                ('start_date', models.DateTimeField(verbose_name='date de début')),
                ('end_date', models.DateTimeField(verbose_name='date de fin')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='utilisations maximum')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='utilisations actuelles')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_items', models.ManyToManyField(blank=True, related_name='promotions', to='restaurants.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
                'db_table': 'promotions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemOptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='modificateur de prix')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='restaurants.menuitemoption')),
            ],
            options={
                'verbose_name': "choix d'option",
                'verbose_name_plural': "choix d'options",
                'db_table': 'menu_item_option_choices',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='photos')),
                ('is_verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurants.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('restaurant', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='restaurants_name_cc4837_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city'], name='restaurants_city_2eac77_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['is_active'], name='restaurants_is_acti_05aaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['is_open'], name='restaurants_is_open_34954a_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['average_rating'], name='restaurants_average_e48f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['name'], name='menu_items_name_1ab05b_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_available'], name='menu_items_is_avai_013e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_featured'], name='menu_items_is_feat_1963a3_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['price'], name='menu_items_price_b41372_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('restaurant', 'name')},
        ),
    ]
