# Generated by Django 4.2.7 on 2025-08-07 13:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='numéro de téléphone')),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('restaurant', 'Restaurant'), ('delivery', 'Livreur'), ('admin', 'Administrateur')], default='client', max_length=20, verbose_name="type d'utilisateur")),
                ('address', models.TextField(blank=True, verbose_name='adresse complète')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('is_verified', models.BooleanField(default=False, verbose_name='compte vérifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='compte actif')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="date d'inscription")),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='dernière connexion')),
                ('language', models.CharField(default='fr', max_length=10, verbose_name='langue')),
                ('timezone', models.CharField(default='Africa/Lome', max_length=50, verbose_name='fuseau horaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='avatar')),
                ('bio', models.TextField(blank=True, verbose_name='biographie')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='notifications email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='notifications SMS')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='notifications push')),
                ('profile_public', models.BooleanField(default=True, verbose_name='profil public')),
                ('show_location', models.BooleanField(default=True, verbose_name='afficher localisation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil utilisateur',
                'verbose_name_plural': 'profils utilisateurs',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200, verbose_name='nom du restaurant')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cuisine_type', models.CharField(max_length=100, verbose_name='type de cuisine')),
                ('opening_hours', models.JSONField(default=dict, verbose_name="horaires d'ouverture")),
                ('is_open', models.BooleanField(default=True, verbose_name='ouvert')),
                ('delivery_radius', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='rayon de livraison (km)')),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='commande minimum')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='frais de livraison')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='note moyenne')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name="nombre total d'avis")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil restaurant',
                'verbose_name_plural': 'profils restaurants',
                'db_table': 'restaurant_profiles',
            },
        ),
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Vélo'), ('motorcycle', 'Moto'), ('car', 'Voiture'), ('scooter', 'Scooter')], max_length=50, verbose_name='type de véhicule')),
                ('vehicle_plate', models.CharField(blank=True, max_length=20, verbose_name="plaque d'immatriculation")),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('last_location_update', models.DateTimeField(blank=True, null=True, verbose_name='dernière mise à jour de localisation')),
                ('total_deliveries', models.PositiveIntegerField(default=0, verbose_name='total des livraisons')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='note moyenne')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='gains totaux')),
                ('working_hours', models.JSONField(default=dict, verbose_name='heures de travail')),
                ('preferred_zones', models.JSONField(blank=True, default=list, verbose_name='zones préférées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil livreur',
                'verbose_name_plural': 'profils livreurs',
                'db_table': 'delivery_profiles',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_restrictions', models.JSONField(blank=True, default=dict, verbose_name='restrictions alimentaires')),
                ('favorite_cuisines', models.JSONField(blank=True, default=list, verbose_name='cuisines préférées')),
                ('saved_addresses', models.JSONField(blank=True, default=list, verbose_name='adresses sauvegardées')),
                ('default_payment_method', models.CharField(blank=True, max_length=50, verbose_name='méthode de paiement par défaut')),
                ('auto_tip_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='pourboire automatique (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil client',
                'verbose_name_plural': 'profils clients',
                'db_table': 'client_profiles',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='gérer les utilisateurs')),
                ('can_manage_restaurants', models.BooleanField(default=False, verbose_name='gérer les restaurants')),
                ('can_manage_orders', models.BooleanField(default=False, verbose_name='gérer les commandes')),
                ('can_view_analytics', models.BooleanField(default=False, verbose_name='voir les analytics')),
                ('can_manage_payments', models.BooleanField(default=False, verbose_name='gérer les paiements')),
                ('moderation_level', models.CharField(choices=[('basic', 'Basique'), ('advanced', 'Avancé'), ('super', 'Super')], default='basic', max_length=20, verbose_name='niveau de modération')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil administrateur',
                'verbose_name_plural': 'profils administrateurs',
                'db_table': 'admin_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_ty_578f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
    ]
