# Generated by Django 4.2.7 on 2025-08-07 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('notification_type', models.CharField(choices=[('order_status', 'Statut de commande'), ('delivery_update', 'Mise à jour de livraison'), ('payment', 'Paiement'), ('promotion', 'Promotion'), ('system', 'Système')], max_length=20, verbose_name='type')),
                ('title_template', models.CharField(max_length=255, verbose_name='modèle de titre')),
                ('message_template', models.TextField(verbose_name='modèle de message')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'modèle de notification',
                'verbose_name_plural': 'modèles de notifications',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='notifications email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='notifications SMS')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='notifications push')),
                ('in_app_notifications', models.BooleanField(default=True, verbose_name="notifications dans l'app")),
                ('order_status_notifications', models.BooleanField(default=True, verbose_name='notifications statut commande')),
                ('delivery_update_notifications', models.BooleanField(default=True, verbose_name='notifications livraison')),
                ('payment_notifications', models.BooleanField(default=True, verbose_name='notifications paiement')),
                ('promotion_notifications', models.BooleanField(default=True, verbose_name='notifications promotion')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='notifications système')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préférence de notification',
                'verbose_name_plural': 'préférences de notifications',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_status', 'Statut de commande'), ('delivery_update', 'Mise à jour de livraison'), ('payment', 'Paiement'), ('promotion', 'Promotion'), ('system', 'Système')], max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='données supplémentaires')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('is_sent', models.BooleanField(default=False, verbose_name='envoyé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
